{% set name = "Pyzotero" %}
{% set version = "1.4.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 945d9e40f43c861ec7cec263925f181e4364aea67d1d3e7389d56ab0616258ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - feedparser >=5.1.0,<6.0.0
    - pytz
    - requests >=2.21.0
    - pathlib
    - bibtexparser

test:
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
