{% set name = "Pyzotero" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 633b31acc70562ae62c5953c46611725211e778f5d3f7f7b0e933ba43d55bbfa

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - feedparser >=5.1.0
    - pytz
    - requests
    - pathlib
    - bibtexparser

test:
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: 'Python wrapper for the Zotero API'
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
