{% set name = "Pyzotero" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b4405557901000ad72d2835c959bb8d0dea4736b0de27995cd6fb0cd3920016

build:
  noarch: python
  number: 0
  script:
    - rm pyproject.toml  # [unix]
    - del pyproject.toml  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - feedparser >=6
    - pytz
    - requests >=2.21.0
    - pathlib
    - bibtexparser

test:
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
