travis:
  secure:
    BINSTAR_TOKEN: 3r6Mtl6Dflguq0kCz2ukE1EeuXitziP0WrCmDD3IkR+7l5sIOY4O2XaSfUUWuVVJi/ycJSo0mh37JzgxbHSdWSaBaCRU9ZYhEqTHt6/IiwD4Any6z39WwNkv1MDE1Z/CLihc8Z4zkLcDzYBjFriDWTiAjYuB/fO3X5/FsAJbjsmKovGKjCQ1lxMCGHdkQ4+A8Lu+HnZweP4TOZ/VZWYDzRnh3yH+XQmiscvMyPHnqjfHHvmxx4D5IcwwEGGhLgVZO6WAZ4mlNbkVb09K2afxyhTIyiFOf/FwhZflktc4dyM97GTH25OQKIfaunujpb9vKL+4v18v5jkOu8U7h0N4YBl241Tg2PiF4uprDcZWbS/vevE7btexiGEB+58fDc1KBtYXWswNDhJzQEBwk7Lq69r0v5I2jYYk57EsQW+vwjq45aYOH6907u/AzS7FiIZp+aVrfu2bdysLCAu72z6MnV81aQLU1RKRh/FnJiUQqqJe5nzEdam8CDZJXiQ88ewtDC+YqQ/HM7ZyPkmE5w7rilDG8cld95XlGp2Ic7s9qk4z8qsCDRqrgRnngTwymIKm7DdO+XDTYDMEFfZAGHhlJFWaPIRQ4q4w1dMPRe+Jf28OKu1qmfTLPt4PZ9STDc78ya5BJz5BKTBnQwX/ORPccKZTrHoHwxqto5CCYF7abC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
