travis:
  secure:
    BINSTAR_TOKEN: JMOTlyPxDpTquHiDZaTDYnSNgctpZqMzuNuU8Fef7m7usPEOIikzo2vd8TEqVqMHIO18yyLIavCjf7Jz0twWIvmMebeP1XZT3gyTgAphjVCAE1j9QLmbrTEGnVaxhnihHLMZL6B8butvWOwaJoY4L/XmfFXghyCeV5lO01Vix1T6TAPoXSkF2SooPc16y+G4bDl/dCmrr3e0mfp4JcADLTeKp8RtP6A+JaQHxu29NRS7EljF3LCbZdHWp7HrOhHznkDlqkDoyfCJrWuj3k2EeyzJ7kHACm8bTbhO+zDVaSxZMOm8CWsJVCiyggP4gzkrKZPiXULp2HmOXSyOZDpKQC/XkX2kpuaFPC4ERG3jY/YyYNmz8t/+wC1fdXWxNOUiG0ed/NR2THUqGZ1fkKt4Bn3UJIb4Lb7YX4H+QExdfuIbFS4XWOu+IrYsLU43nYyVLxO/5H97blQGLz8zsVHbZO3z6UC8LKFQ/xn/4xNtt+rwxV1U/9lEofraDwUPPDleiFplJy+KzUG1vGDnnX9EQrFBjO74arIK363ZWC/ooZL04tx+c+oypbmm1mVXb84PcAp8VXfROGj3mKGek9rXVqdvc2ZfWAuCKrr9j78eA1/mYUirKQVav7QLbMSvOFJ+k6UPE2TlECmUjEBLUWbLRxUnrj0ol+A2A1/QbFbhYg8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
